language: scala

os:
  - linux
jdk:
  - oraclejdk8
sudo: required
dist: trusty

install:
  - mvn install dependency:go-offline -Pskip-formatter -DskipTests=true -q -f driver/pom.xml -Dfailsafe.timeout=0

script:
  - mvn install -P travis -B -f driver/pom.xml -Dfailsafe.timeout=0
  - cd tests-scala ; sbt test
